trigger:
  - master

resources:
  repositories:
    - repository: templates
      type: github
      name: RaaLabs/EdgeTools
      endpoint: RaaLabs/EdgeTools

jobs:
  - template: AzureDevOps/DotNet/pipeline.yml
